version: "3.3"
services:
  mysqldb:
    image: mysql/mysql-server:latest
    env_file: ./.env
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_LOCAL_PORT
    volumes:
      - mysqldbvol:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
    build: .
    container_name: backend
    #image: backend
    image: brightdeanz/devops-spring-server
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_LOCAL_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_LOCAL_PORT/$MYSQLDB_DATABASE?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_PASSWORD",
    		"spring.jpa.generate-ddl" : "true",
    		"spring.thymeleaf.cache" : "true",
			"spring.thymeleaf.check-template" : "true",
			"spring.thymeleaf.enabled" : "true",
			"spring.thymeleaf.enable-spring-el-compiler" : "false",
			"spring.thymeleaf.mode" : "HTML",
			"spring.thymeleaf.prefix" : "/WEB-INF/pages/",
			"spring.thymeleaf.suffix" : ".html",
			"spring.web.resources.add-mappings" : "true"
		
		}'
  frontend:
    depends_on:
      - backend
    container_name: frontend
    build: ../kubernetes-deploy-frontend
    #image: frontend
    image: brightdeanz/devops-react-server
    ports:
      - 3000:3000
    restart: on-failure
volumes:
  mysqldbvol:
