apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  config.json:
    '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-cluster-ip/dsDb0?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "user0",
        "spring.datasource.password" : "changeit",
    		"spring.jpa.generate-ddl" : "true",
    		"spring.thymeleaf.cache" : "true",
			"spring.thymeleaf.check-template" : "true",
			"spring.thymeleaf.enabled" : "true",
			"spring.thymeleaf.enable-spring-el-compiler" : "false",
			"spring.thymeleaf.mode" : "HTML",
			"spring.thymeleaf.prefix" : "/WEB-INF/pages/",
			"spring.thymeleaf.suffix" : ".html",
			"spring.web.resources.add-mappings" : "true"
		
		}'
    
